### ISSUE TITLE
Don't use links to include style sheet try to download and include in directory

### ISSUE THREAD

**Issue by ibigrock-ashish** [ibigrock-karan/960-grid#9]
<link href='http://fonts.googleapis.com/css?family=Acme' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Amita' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Aclonica' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="css/plugins/font-awesome/css/font-awesome.min.css">

**Comment by mekaransethi** [comment]
done
